@ -1,29 +0,0 @@
services:
  - type: web
    name: laravel-backend
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./backend/Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: your-app-key-here
      - key: APP_URL
        value: https://laravel-backend.onrender.com
      # Add these if you use a database
      # - key: DB_CONNECTION
      #   value: mysql
      # - key: DB_HOST
      #   value: your-db-host
      # - key: DB_PORT
      #   value: 3306
      # - key: DB_DATABASE
      #   value: your-db-name
      # - key: DB_USERNAME
      #   value: your-db-user
      # - key: DB_PASSWORD
      #   value: your-db-password